styled-components applied
jessicaarrais/recipes-app pull request #70
Opened 2020-10-10 17:15 UTC by jessicaarrais

2020-10-12 19:17 UTC, davicatunda requested changes
I've being thinking, I think we need a naming convention for Styled components. Can you search a little bit on the web how other people are doing this? I found one article: https://medium.com/inturn-eng/naming-styled-components-d7097950a245

But perhaps we can choose our own convention. How about if components that are styled always ended or started with some word? the article uses an object called "S", but we could also not create any object and just name things with a weird characted, like replacing "Likes" with "Likes$Styles" or "S$Likes" or anything that you feel like doing to make clearer that the component is not a component but a style.

On another note, some of this component will eventually be replaced with components from the component Library, the more "real" components we use, the easier it is to have your entire site consistent style wise.

2020-10-12 19:17 UTC, davicatunda commented on src/components/recipe/recipe-page-ingredients/RecipePageIngredients.tsx
> +const Ingredient = styled.li`
maybe call ListItem

2020-10-12 19:17 UTC, davicatunda commented on src/components/recipe/recipe-page-instructions/RecipePageInstructions.tsx
> +const Instruction = styled.li`
maybe call InstructionListItem

2020-10-12 19:17 UTC, davicatunda commented on src/index.tsx
> +  }
this is not going to be needed once you use typography components

2020-10-12 20:19 UTC, jessicaarrais commented on src/components/UserProfileButton.tsx
> +  font-weight: bold;
right! get it!
it was serving a purpose that has been lost.

2020-10-12 20:20 UTC, jessicaarrais commented on src/components/UserProfileButton.tsx
> +  font-size: 12px;
it is resizing the avatar img

2020-10-12 20:31 UTC, jessicaarrais commented on src/components/cookbook/Cookbook.tsx
> +  display: flex;
no. I can remove it and reconfigure its sibling div.

2020-10-12 20:39 UTC, jessicaarrais commented on src/components/cookbook/Cookbook.tsx
> +`;
makes sense

2020-10-12 20:40 UTC, jessicaarrais commented on src/components/cookbook/Cookbook.tsx
> -    <div className="sort-list-container" onClick={handleOnSortList}>
wrongly put

2020-10-12 20:40 UTC, jessicaarrais commented on src/components/UserProfileButton.tsx
> +  font-weight: bold;
also, I like the S object ideia

2020-10-12 20:47 UTC, jessicaarrais commented on src/components/ingredient/Ingredient.tsx
> +    <IngredientList
Yes. Maybe I am being excessively repetitive

2020-10-12 21:01 UTC, jessicaarrais commented on src/components/instruction/Instruction.tsx
> +  width: 100%;
must be reviewed

2020-10-12 21:03 UTC, jessicaarrais commented on src/components/login-signup/Login.tsx
> +  background-color: #ffffff;
colors and design still need to be reviewed/chosen

2020-10-12 23:08 UTC, jessicaarrais commented on src/components/navigation-bar/NavigationBar.tsx
> +`;
it is. the name is wrong. should be 'LeftItems'

2020-10-13 17:07 UTC, jessicaarrais commented on src/components/login-signup/Login.tsx
> +`;
it will be implemented in a next diff

2020-10-13 19:59 UTC, davicatunda approved these changes

2020-10-13 20:05 UTC, merged